export default {
  data() {
    return {}
  },
  methods: {
    initDemoData() {
      if (this.$route.query.t && this.$route.query.t === '1') this.generateGraph()
    },
    /**
     * [generateGraph 模拟数据]
     * @return {[type]} [description]
     */
    generateGraph() {
      if (this.chartData.nodeDataArray.length > 0) return false
      this.chartData = {
        nodeDataArray: [{
          'key': 1,
          keyword: '440104198312055318',
          'category': 'person',
          'text': '李浩鹏',
          type: '4',
          'color': '#fff',
          source: `${this.personImagePath}440104198312055318`,
          'isHit': false
        }, {
          'key': 2,
          keyword: '440981199205297814',
          'category': 'person',
          'text': '骆健儿',
          type: '4',
          'color': '#fff',
          source: `${this.personImagePath}440981199205297814`,
          'isHit': false
        }, {
          'key': 3,
          keyword: '431228198412255224',
          'category': 'person',
          'text': '李义珍',
          type: '4',
          'color': '#fff',
          source: `${this.personImagePath}431228198412255224`,
          'isHit': false
        }, {
          'key': 4,
          keyword: '452426198101083616',
          'category': 'person',
          'text': '李达康',
          type: '4',
          'color': '#fff',
          source: `${this.personImagePath}452426198101083616`,
          'isHit': false
        }, {
          'key': 5,
          keyword: '43122719870802092X',
          'category': 'person',
          'text': '吴惠芬',
          type: '4',
          'color': '#fff',
          source: `${this.personImagePath}43122719870802092X`,
          'isHit': false
        }, {
          'key': 6,
          keyword: '430524199010116701',
          'category': 'person',
          'text': '钟小艾',
          type: '4',
          'color': '#fff',
          source: `${this.personImagePath}430524199010116701`,
          'isHit': false
        }, {
          'key': 7,
          keyword: '342921199303051828',
          'category': 'person',
          'text': '高育良',
          type: '4',
          'color': '#fff',
          source: `${this.personImagePath}342921199303051828`,
          'isHit': false
        }, {
          'key': 8,
          keyword: '360521198804083225',
          'category': 'person',
          'text': '夏侯亮平',
          type: '4',
          'color': '#fff',
          source: `${this.personImagePath}360521198804083225`,
          'isHit': false
        }, {
          'key': 9,
          keyword: '45223119791206051X',
          'category': 'person',
          'text': '袁林双',
          type: '4',
          'color': '#fff',
          source: `${this.personImagePath}45223119791206051X`,
          'isHit': false
        }, {
          'key': 10,
          keyword: '430521198908030054',
          'category': 'person',
          'text': '周正泽',
          type: '4',
          'color': '#fff',
          source: `${this.personImagePath}430521198908030054`,
          'isHit': false
        }, {
          'key': 11,
          keyword: '433021196405094810',
          'category': 'person',
          'text': '龙林双',
          type: '4',
          'color': '#fff',
          source: `${this.personImagePath}433021196405094810`,
          'isHit': false
        }, {
          'key': 12,
          keyword: '430103197602071030',
          'category': 'person',
          'text': '陈海波',
          type: '4',
          'color': '#fff',
          source: `${this.personImagePath}430103197602071030`,
          'isHit': false
        }, {
          'key': 13,
          keyword: '431225199612220224',
          'category': 'person',
          'text': '林华华',
          type: '4',
          'color': '#fff',
          source: `${this.personImagePath}431225199612220224`,
          'isHit': false
        }, {
          'key': 14,
          keyword: '411423198308196039',
          'category': 'person',
          'text': '赵东来',
          type: '4',
          'color': '#fff',
          source: `${this.personImagePath}411423198308196039`,
          'isHit': false
        }, {
          'key': 15,
          keyword: '432326197610105816',
          'category': 'person',
          'text': '陈永世',
          type: '4',
          'color': '#fff',
          source: `${this.personImagePath}432326197610105816`,
          'isHit': false
        }, {
          'key': 16,
          keyword: '433024196903022712',
          'category': 'person',
          'text': '陈士江',
          type: '4',
          'color': '#fff',
          source: `${this.personImagePath}433024196903022712`,
          'isHit': false
        }, {
          'key': 17,
          keyword: '433027197911301619',
          'category': 'person',
          'text': '李昌明',
          type: '4',
          'color': '#fff',
          source: `${this.personImagePath}433027197911301619`,
          'isHit': false
        }],
        linkDataArray: [{
          'from': 1,
          'to': 2,
          'text': '指使',
          'color': '#000',
          'visible': true
        }, {
          'from': 2,
          'to': 3,
          'text': '合作关系',
          'color': '#8bc63a',
          'visible': true
        }, {
          'from': 3,
          'to': 4,
          'text': '杀害',
          'color': '#000',
          'visible': true
        }, {
          'from': 4,
          'to': 7,
          'text': '竞争对手',
          'color': '#5c92fa',
          'visible': true
        }, {
          'from': 7,
          'to': 5,
          'text': '挚友',
          'color': '#5c92fa',
          'visible': true
        }, {
          'from': 12,
          'to': 7,
          'text': '学生',
          'color': '#8bc63a',
          'visible': true
        }, {
          'from': 6,
          'to': 8,
          'text': '夫妻',
          'color': '#f0acad',
          'visible': true
        }, {
          'from': 8,
          'to': 7,
          'text': '学生',
          'color': '#8bc63a',
          'visible': true
        }, {
          'from': 8,
          'to': 1,
          'text': '发小',
          'color': '#8bc63a',
          'visible': true
        }, {
          'from': 8,
          'to': 12,
          'text': '同学',
          'color': '#8bc63a',
          'visible': true
        }, {
          'from': 8,
          'to': 11,
          'text': '得力下属',
          'color': '#5c92fa',
          'visible': true
        }, {
          'from': 12,
          'to': 9,
          'text': '老学长',
          'color': '#8bc63a',
          'visible': true
        }, {
          'from': 12,
          'to': 7,
          'text': '学生',
          'color': '#8bc63a',
          'visible': true
        }, {
          'from': 11,
          'to': 12,
          'text': '喜欢',
          'color': '#f0acad',
          'visible': true
        }, {
          'from': 11,
          'to': 10,
          'text': '下属',
          'color': '#5c92fa',
          'visible': true
        }, {
          'from': 11,
          'to': 13,
          'text': '下属',
          'color': '#5c92fa',
          'visible': true
        }, {
          'from': 14,
          'to': 11,
          'text': '对其有意',
          'color': '#f0acad',
          'visible': true
        }, {
          'from': 10,
          'to': 13,
          'text': '情侣',
          'color': '#f0acad',
          'visible': true
        }, {
          'from': 15,
          'to': 12,
          'text': '父亲',
          'color': '#5c92fa',
          'visible': true
        }, {
          'from': 16,
          'to': 12,
          'text': '母亲',
          'color': '#5c92fa',
          'visible': true
        }, {
          'from': 15,
          'to': 16,
          'text': '夫妻',
          'color': '#f0acad ',
          'visible': true
        }, {
          'from': 17,
          'to': 12,
          'text': '上属领导',
          'color': '#5c92fa',
          'visible': true
        }]
      }
      // this.$refs.analysisRelationGoBox.initMaker()
      let self = this
      setTimeout(() => {
        self.setLayout('LayeredDigraphLayout', 'analysisRelationGoBox')
      }, 300)
    }
  }
}
