/**
 * 公安默认字段翻译map
 * @type {String}
 */
export default {
  lkbh: '旅客编号',
  hjdz: '户籍地址',
  xm: '姓名',
  zjhm: '证件号码',
  fxrxm: '分析人姓名',
  fxrzjhm: '分析人证件号码',
  lkgh: '旅客编号',
  xb: '性别',
  csrq: '出生日期',
  mz: '民族',
  lgbm: '旅馆编码',
  rzsj: '入住时间',
  tfsj: '退房时间',
  rzfh: '入住房号',
  lgmc: '旅馆名称',
  lgdz: '旅馆地址',
  kssj: '开始时间',
  jssj: '结束时间',
  wbdm: '网吧代码',
  wbmc: '网吧名称',
  wbdz: '网吧地址',
  ccrq: '乘车日期',
  ccsj: '乘车时间',
  cc: '车次',
  fz: '出发站',
  dz: '到达站',
  cxh: '车厢号',
  zwh: '座位号',
  pz: '票种',
  hbh: '航班号',
  hb_rq: '航班日期',
  // lg_rq: '离岗日期',
  // jg_rq: '进岗日期',
  // qfhzsz: '始发地',
  // dahzsz: '目的地',
  lkzw: '旅客座位',
  fxjdchphm: '分析机动车号牌号码',
  kkbh: '卡口编号',
  kkmc: '卡口名称',
  cdbh: '车道编号',
  jdchphm: '机动车号牌号码',
  tgfx: '方向',
  jdccllx: '车辆类型',
  clsd: '车辆速度',
  tgsj: '通过时间',
  cnt: '频繁次数',
  // kssj: '开始上网时间',
  // jssj: '结束上网时间',
  txcs: '同行次数',
  ph: '票号',
  lg_rq: '离港日期',
  jg_rq: '进港日期',
  qfhzsz: '起飞航站代码',
  dahzsz: '到达航站代码',
  gprq: '购票日期',
  cplx: '车票类型',
  sfd: '始发地',
  mdd: '目的地'
}
